name: ConfigurableElytraNerfs
version: 1.0.2
main: com.cosmicsubspace.mc.cen.ConfigurableElytraNerfs
description: Nerfs Elytras... configurably.
authors: [CosmicSubspace, FemBoysAreCut3]
commands:
    cen:
        description: Print info about CEN plugin
